spring.application.name=NexusOS
spring.profiles.active=dev
server.port=8080

logging.level.root=INFO
logging.level.com.nexusos=DEBUG

# mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=your-email@gmail.com
spring.mail.password=your-app-password

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.frontend-url=http://localhost:8080

# JWT Configuration
jwt.secret=ReplaceThisWithAVeryLongRandomSecretKeyAtLeast32CharactersLong
jwt.expiration=3600000